function submitForm(event) {
    event.preventDefault(); // Prevents the default form submission action

    const apiUrl = 'http://localhost:5241/Order'; // Your API URL

    const currentDate = new Date().toISOString();

    const formData = {
        orderID: 0, // Assuming this is handled or generated by your backend
        customerName: document.getElementById('customerName').value,
        customerEmail: document.getElementById('email').value,
        customerPhone: document.getElementById('phone').value,
        priority: document.getElementById('priority').value,
        serviceType: document.getElementById('serviceType').value,
        createDate: currentDate, 
        pickupDate: currentDate, // Modify as required
        status: 'Offen', // Adjust this as needed
        comment: ''
    };

    fetch(apiUrl, {
        method: 'POST',
        headers: {
            'accept': 'text/plain',
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(formData)
    })
    .then(response => {
        if (!response.ok) {
            throw new Error('Network response was not ok');
        }
        return response.text();
    })
    .then(data => {
        console.log('Success:', data);
        // Handle success - maybe display a success message
    })
    .catch((error) => {
        console.error('Error:', error);
        // Handle errors here, such as displaying an error message
    });
}
